### ISSUE TITLE
Report Pod/Container status in Deployed condition

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-sources#73]
### Problem

Event sources surface the status of Services/Deployments in the `Deployed` status condition. Unfortunately, Services/Deployments only report a high-level error in case of failure:

```yaml
- lastTransitionTime: "2020-08-12T10:44:24Z"
  message: 'The adapter Deployment is unavailable: Deployment does not have minimum availability.'
  reason: AdapterUnavailable
  status: "False"
  type: Deployed
```

This is not useful for troubleshooting because one needs to inspect the underlying Pods to understand what's going on. In this case, the receive adapter's container was missing a Secret:

```yaml
  containerStatuses:
  - image: gcr.io/triggermesh/awsdynamodbsource:ba2dd9983d11956c60129e163b1acbe8ed3f2354
    imageID: ""
    lastState: {}
    name: adapter
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: secret "awscreds" not found    # <---------- this
        reason: CreateContainerConfigError
```

### Proposal

In case of unavailable Service/Deployment, we could attempt to bubble up the actual error by going over the Pods that belong to that Service/Deployment and reading their status. Here is how the above example could look like with the addition of Pod statuses:

```yaml
- lastTransitionTime: "2020-08-12T10:44:24Z"
  message: 'The adapter Deployment is unavailable: secret "awscreds" not found'
  reason: CreateContainerConfigError
  status: "False"
  type: Deployed
```

We could even go one step further and expose even more granular `reasons`, such as `MissingSecret` in case the message is about a Secret, etc.

cc. @odacremolbap, since we discussed it together
