### ISSUE TITLE
Zendesk: wrong propagation of Ready condition

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-sources#78]
The Zendesk source reports its status using 2 separate conditionSets:

* `eventSourceConditionSet`, a generic conditionSet used by all sources across the TriggerMesh landscape
* `zendeskSourceConditionSet`, which is used to inject the extra `TargetSynced` condition on top of the generic conditions

There is one issue with the current design. Because the `Ready` condition is included in both conditionSets, the `TargetSynced` condition is always marked as the "terminal" condition, even when another condition such as `Deployed` has a more recent transition time.

See the following example:

```yaml
  conditions:
  - lastTransitionTime: "2020-08-13T01:49:43Z"     # <------------- recent
    message: 'The adapter Service is unavailable; Configuration "zendesksource-sample"
      does not have any ready Revision.; Revision "zendesksource-sample-pp6k6"
      failed with message: secret "zendesksource" not found.'
    reason: MissingSecret
    status: "False"
    type: Deployed
  - lastTransitionTime: "2020-08-13T01:47:39Z"
    message: The receive adapter did not report its public URL yet
    reason: FailedSync
    status: "False"
    type: Ready
  - lastTransitionTime: "2020-08-13T01:46:17Z"
    status: "True"
    type: SinkProvided
  - lastTransitionTime: "2020-08-13T01:47:39Z"     # <------------- older
    message: The receive adapter did not report its public URL yet
    reason: FailedSync
    status: "False"
    type: TargetSynced
```

Here, the `Deployed` condition transitioned _after_ the `TargetSynced` condition was last updated, so I would expect the `Ready` condition to reflect the reason+message of the `Deployed` condition. Yet, as you can see, the `Ready` condition shows the reason+message of the `TargetSynced` condition.

I'm not certain how to tackle this, we probably need to pass the expected conditionSet to `GenericServiceReconciler` as an override, but that would also mean ensuring `zendeskSourceConditionSet` is a superset of `eventSourceConditionSet`.

Here's the Knative code that propagates the reason+message to the `Ready` condition based on the transition time:
https://github.com/knative/pkg/blob/c4576fd3/apis/condition_set.go#L284-L292
